# Generated by Django 2.1.7 on 2019-06-17 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(default='', max_length=15, verbose_name='Telefone')),
                ('cpf', models.CharField(default='', max_length=11, verbose_name='CPF')),
                ('email', models.CharField(default='', max_length=100, verbose_name='e-Mail')),
                ('data_nasc', models.CharField(default='', max_length=10, verbose_name='Data de Nascimento')),
            ],
        ),
        migrations.CreateModel(
            name='Clinico',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='transplante.Pessoa')),
                ('id_clinico', models.AutoField(primary_key=True, serialize=False)),
                ('setor', models.CharField(default='', max_length=100, verbose_name='Setor')),
                ('profissao', models.CharField(default='', max_length=50, verbose_name='Profissão')),
                ('CRM_CRE', models.CharField(default='', max_length=50, verbose_name='CRM ou CRE')),
                ('especialidade', models.CharField(default='', max_length=100, verbose_name='Especialidade')),
            ],
            bases=('transplante.pessoa',),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transplante.Pessoa')),
                ('tipo_sanguineo', models.CharField(default='', max_length=3, verbose_name='Tipo Sanguíneo')),
                ('orgao', models.CharField(default='', max_length=20, verbose_name='Órgão')),
                ('alergia', models.CharField(default='', max_length=100, verbose_name='Alergias')),
                ('doenca_preexist', models.CharField(default='', max_length=100, verbose_name='Doença Pré-existente')),
            ],
            bases=('transplante.pessoa',),
        ),
        migrations.CreateModel(
            name='Secretario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transplante.Pessoa')),
            ],
            bases=('transplante.pessoa',),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
