# Generated by Django 2.1.7 on 2019-06-18 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transplante', '0002_remove_pessoa_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirurgia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.CharField(default='', max_length=30, verbose_name='Data e hora da Cirurgia')),
                ('sala_cirurgia', models.CharField(default='', max_length=15, verbose_name='Sala da Cirurgia')),
                ('sala_recuperacao', models.CharField(default='', max_length=15, verbose_name='Sala de Recuperação')),
                ('tempo_duracao', models.CharField(default='', max_length=30, verbose_name='Tempo de Duração da Cirurgia')),
                ('equipamento', models.CharField(default='', max_length=100, verbose_name='Equipamento Necessário')),
                ('doador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doador', to='transplante.Paciente')),
                ('enfermeiro_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enfermeiro', to='transplante.Clinico')),
                ('medico_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medico', to='transplante.Clinico')),
                ('receptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receptor', to='transplante.Paciente')),
            ],
        ),
    ]
