# Generated by Django 2.1.7 on 2019-04-29 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplante', '0002_auto_20190429_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='alergia',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='doenca_preexist',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='paciente',
            name='orgao',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sanguineo',
            field=models.CharField(default='', max_length=3),
        ),
    ]
