# Generated by Django 2.1.7 on 2019-06-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplante', '0003_cirurgia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cirurgia',
            name='orgao',
            field=models.CharField(default='', max_length=20, verbose_name='Órgão'),
        ),
    ]
