# Generated by Django 2.1.7 on 2019-04-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplante', '0003_auto_20190429_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_nasc',
            field=models.CharField(default='', max_length=10),
        ),
    ]
