# Generated by Django 2.1.7 on 2019-06-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplante', '0004_cirurgia_orgao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cirurgia',
            name='data_hora',
            field=models.DateTimeField(default='', max_length=30, verbose_name='Data e hora da Cirurgia'),
        ),
    ]
