# Generated by Django 2.1.7 on 2019-05-10 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transplante', '0004_pessoa_data_nasc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinicos',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='transplante.Pessoa')),
                ('id_clinicos', models.AutoField(primary_key=True, serialize=False)),
                ('setor', models.CharField(default='', max_length=100)),
                ('profissao', models.CharField(default='', max_length=50)),
                ('CRM_CRE', models.CharField(default='', max_length=50)),
                ('especialidade', models.CharField(default='', max_length=100)),
            ],
            bases=('transplante.pessoa',),
        ),
    ]
