# Generated by Django 2.1.7 on 2019-06-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplante', '0005_auto_20190618_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='cirurgia',
            name='data_hora',
            field=models.DateTimeField(default='', max_length=30, verbose_name='Data e Hora da Cirurgia'),
        ),
    ]
