# Generated by Django 2.1.7 on 2019-05-29 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transplante', '0006_auto_20190513_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinico',
            old_name='id_clinicos',
            new_name='id_clinico',
        ),
    ]
