# Generated by Django 2.1.7 on 2019-06-17 18:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transplante', '0007_auto_20190529_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretario',
            name='id_secretario',
            field=models.AutoField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinico',
            name='CRM_CRE',
            field=models.CharField(default='', max_length=50, verbose_name='CRM ou CRE'),
        ),
        migrations.AlterField(
            model_name='clinico',
            name='especialidade',
            field=models.CharField(default='', max_length=100, verbose_name='Especialidade'),
        ),
        migrations.AlterField(
            model_name='clinico',
            name='profissao',
            field=models.CharField(default='', max_length=50, verbose_name='Profissão'),
        ),
        migrations.AlterField(
            model_name='clinico',
            name='setor',
            field=models.CharField(default='', max_length=100, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alergia',
            field=models.CharField(default='', max_length=100, verbose_name='Alergias'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='doenca_preexist',
            field=models.CharField(default='', max_length=100, verbose_name='Doença Pré-existente'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='orgao',
            field=models.CharField(default='', max_length=20, verbose_name='Órgão'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='tipo_sanguineo',
            field=models.CharField(default='', max_length=3, verbose_name='Tipo Sanguíneo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='', max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nasc',
            field=models.CharField(default='', max_length=10, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='e-Mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default='', max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(default='', max_length=15, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='secretario',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='transplante.Pessoa'),
        ),
    ]
