# Generated by Django 2.1.7 on 2019-06-17 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transplante', '0008_auto_20190617_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretario',
            name='id_secretario',
        ),
        migrations.AlterField(
            model_name='secretario',
            name='pessoa_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='transplante.Pessoa'),
        ),
    ]
