# Generated by Django 2.1.7 on 2019-06-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplante', '0009_auto_20190618_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='subject',
        ),
        migrations.AddField(
            model_name='paciente',
            name='doador_receptor',
            field=models.CharField(default='', max_length=30, verbose_name='Doador ou Receptor'),
        ),
    ]
