# Generated by Django 2.1.7 on 2019-06-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transplante', '0010_auto_20190618_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretario',
            name='registro_funcionario',
            field=models.CharField(default='', max_length=50, verbose_name='Registro do Funcionário'),
        ),
    ]
